name: Build EXE
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        # 폴더 경로를 지정하여 실행합니다
        run: dotnet restore ED9FontConverter/ED9FontConverter.csproj

      - name: Build
        # 폴더 경로와 리스토어 금지 옵션을 추가합니다
        run: dotnet build ED9FontConverter/ED9FontConverter.csproj --configuration Release --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ED9FontConverter-EXE
          # 빌드된 결과물 위치를 정확히 지정합니다
          path: "ED9FontConverter/bin/Release/**/ED9FontConverter.exe"
