name: Build EXE
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        # 현재 위치와 모든 하위 폴더에서 .csproj 파일을 찾아 리스토어합니다.
        run: dotnet restore (Get-ChildItem -Filter *.csproj -Recurse).FullName
        shell: pwsh

      - name: Build
        # 찾은 프로젝트 파일을 릴리즈 모드로 빌드합니다.
        run: dotnet build (Get-ChildItem -Filter *.csproj -Recurse).FullName --configuration Release --no-restore
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ED9FontConverter-EXE
          # 빌드된 결과물 폴더 전체를 가져옵니다.
          path: "**/bin/Release/**/ED9FontConverter.exe"
